name: skydive
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  flash: ^3.1.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  firebase_core: ^3.14.0
  shared_preferences: ^2.5.3
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0
  country_code_picker: ^3.4.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  logger: ^2.6.1
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.13.1
  circular_countdown_timer: ^0.2.4
  carousel_slider: ^5.1.1
  html: ^0.15.6
  dotted_border: ^2.0.0
  collection: ^1.19.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200
